'use client';

import { Navbar } from '@/components/Navbar';
import { PUBLIC_GOODS_RECIPIENTS } from '@/lib/constants';
import { Heart, ExternalLink } from 'lucide-react';

export default function PublicGoodsPage() {
  return (
    <div className="min-h-screen bg-gray-50">
      <Navbar />
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <h1 className="text-3xl font-bold text-gray-900 mb-4">Public Goods</h1>
        <p className="text-gray-600 mb-8">
          A portion of the yield generated by the vault is automatically donated to these public goods projects.
        </p>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-8">
          {PUBLIC_GOODS_RECIPIENTS.map((recipient) => (
            <div
              key={recipient.address}
              className="bg-white rounded-xl p-6 shadow-sm border border-gray-200"
            >
              <div className="flex items-start justify-between mb-4">
                <div>
                  <h3 className="text-xl font-semibold text-gray-900 mb-2">{recipient.name}</h3>
                  <p className="text-gray-600 text-sm mb-4">{recipient.description}</p>
                </div>
                <Heart className="h-6 w-6 text-red-500" />
              </div>
              <div className="space-y-2 mb-4">
                <div className="flex justify-between">
                  <span className="text-gray-600">Address</span>
                  <span className="font-mono text-sm text-gray-900">
                    {recipient.address.slice(0, 6)}...{recipient.address.slice(-4)}
                  </span>
                </div>
                <div className="flex justify-between">
                  <span className="text-gray-600">Total Received</span>
                  <span className="font-semibold">$0</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-gray-600">Allocation</span>
                  <span className="font-semibold">50%</span>
                </div>
              </div>
              <a
                href={`https://etherscan.io/address/${recipient.address}`}
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center text-teal-600 hover:text-teal-700 text-sm font-medium"
              >
                View on Etherscan
                <ExternalLink className="ml-2 h-4 w-4" />
              </a>
            </div>
          ))}
        </div>

        <div className="bg-gradient-to-r from-teal-600 to-purple-600 rounded-xl p-8 text-white">
          <h2 className="text-2xl font-bold mb-4">How It Works</h2>
          <p className="mb-4">
            When yield is harvested from the vault, 20% is automatically routed to the ImpactHook,
            which distributes the funds to public goods recipients based on their allocation percentages.
          </p>
          <p>
            All donations are fully on-chain and transparent. You can verify every transaction on Etherscan.
          </p>
        </div>
      </div>
    </div>
  );
}

